spring.application.name=spot-admission-portal
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/cet_students
spring.datasource.username=harsh
spring.datasource.password=2912
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# application.properties
razorpay.key.id=rzp_test_TIwYMcbmkkEfHP
razorpay.key.secret=QIpQ5xRS7oYmHMloGVAxzsmT
# Explicitly informs Hibernate to use PostgreSQL syntax features
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB
# ===================================================================
# ⚡ HIGH-PERFORMANCE BATCH SETTINGS (CRITICAL FOR EXCEL IMPORT)
# ===================================================================
# Instead of doing 800,000 slow round-trips to the database one row at a time,
# these settings bundle them into swift blocks of 50 records at once.
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
